env:
- REPORT_CARD_GITHUB_STATUS_TOKEN=$$report_card_github_status_token
- REPORT_CARD_GITHUB_REPO_TOKEN=$$report_card_github_repo_token
image: clever/drone-go:1.5
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  catapult:
    url: $$catapult_url
    application: "postgres-to-redshift"
    when:
      branch: master
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/postgres-to-redshift
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
